### ISSUE TITLE
Field value = NULL errors out

### ISSUE THREAD

**Issue by mjonssonme** [slabody/pdf_manager#21]
Hey,
So just noticed, if you try to pass a field from a table that has no value - null, it fails.

![image](https://user-images.githubusercontent.com/7919911/162053530-c1ed002a-add7-47a6-9a6a-ba57b32e7af4.png)
This is in the Create PDF action, script step 1

Wonder if it could be fixed by setting all NULL to something blank, but not NULL.

**Comment by slabody** [comment]
Working on update to check for empty field values and if so, just enter in an empty string. Hoping to get that pushed out this weekend.

**Comment by slabody** [comment]
Updated fix into master branch. Now when a record has an empty value there's a check if it's null and if so, it'll be an empty string.

**Comment by slabody** [comment]
Added a null value check for data. Now will only use an empty string.
